<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpillCafe extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert(
            [
                //Toasted Bagels
                [
                    'name' => 'Tomato, Basil pesto', 
                    'price' => 5.50, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '1.jpg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Tomato, basil pesto, Cream Cheese', 
                    'price' => 6.50, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '2.jpg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Salmon, Cream Cheese, Avocado', 
                    'price' => 9, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '3.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Tomato', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '4.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Avocado, Basil Pesto', 
                    'price' => 6, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '5.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Avocado, basil pesto, Tomato', 
                    'price' => 7, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '6.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Avocado, Basil Pesto, Cream cheese', 
                    'price' => 7, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '7.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Avocado, Basil pesto, brie Cheese', 
                    'price' => 8, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '8.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Ham, Tomato, Brie Cheese', 
                    'price' => 8, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '9.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Salmon, Cream Cheese', 
                    'price' => 8.50, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '10.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Salmon, Cream Cheese, Avocado', 
                    'price' => 9, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '11.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Bacoob, Egg, Tomato', 
                    'price' => 8.50, 
                    'ingredients' => '', 
                    'type' => 'toasted bagels',
                    'image' => '12.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                //Flavoured Coffee
                [
                    'name' => 'Caramel Latte', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '13.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Gingerbread Latte', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '14.jpg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Hazelnut Latte', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '15.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Irish Latte', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '16.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Vanila Latte', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '17.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Caramel Macchiato', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '1.jpg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'White Mochaccino', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '2.jpg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Banana Hot Chocolate', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '3.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Turkish Delight Hot Chocolate', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '4.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Cinamon Hot Chocolate', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '5.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Salted Caramel Latte', 
                    'price' => 5, 
                    'ingredients' => '', 
                    'type' => 'flavoured coffee',
                    'image' => '6.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                //cold drinks
                [
                    'name' => 'Iced Coffee', 
                    'price' => 5.90, 
                    'ingredients' => '', 
                    'type' => 'cold drinks',
                    'image' => '7.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Iced Chocolate', 
                    'price' => 5.90, 
                    'ingredients' => '', 
                    'type' => 'cold drinks',
                    'image' => '8.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Iced Mocha', 
                    'price' => 5.90, 
                    'ingredients' => '', 
                    'type' => 'cold drinks',
                    'image' => '9.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Iced Latte', 
                    'price' => 5.90, 
                    'ingredients' => '', 
                    'type' => 'cold drinks',
                    'image' => '10.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Iced Americano', 
                    'price' => 4, 
                    'ingredients' => '', 
                    'type' => 'cold drinks',
                    'image' => '11.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                // teas
                [
                    'name' => 'English Breakfast', 
                    'price' => 3, 
                    'ingredients' => '', 
                    'type' => 'teas',
                    'image' => '12.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Earl Grey', 
                    'price' => 3, 
                    'ingredients' => '', 
                    'type' => 'teas',
                    'image' => '13.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Grean Tea', 
                    'price' => 3, 
                    'ingredients' => '', 
                    'type' => 'teas',
                    'image' => '14.jpg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Herbal Fruit', 
                    'price' => 3, 
                    'ingredients' => '', 
                    'type' => 'teas',
                    'image' => '15.jpeg',
                    'restaurant_id' => 9,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
            ]
        );
    }
}
