<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TheGourmetThai extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert(
            [
                // Entress
                [
                    'name' => 'Thai Spring Rolls (4 pcs)', 
                    'price' => 7, 
                    'ingredients' => 'Deep fried spring rolls filled with vermicelli & veges', 
                    'type' => 'entrees',
                    'image' => '1.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Curry Puffs (4 pcs)', 
                    'price' => 7.50, 
                    'ingredients' => 'Deep fried curry puff with minced chicken, corns, potato & yellow curry', 
                    'type' => 'entrees',
                    'image' => '2.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Phoenix Wings (3 pcs)', 
                    'price' => 8, 
                    'ingredients' => '', 
                    'type' => 'entrees',
                    'image' => '3.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Thai Fish Cakes (5 pcs)', 
                    'price' => 11, 
                    'ingredients' => '', 
                    'type' => 'entrees',
                    'image' => '4.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                //soups
                [
                    'name' => 'Tom Yum Soup', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '5.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Hot Basil', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '6.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Katiam Prik Thai', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '7.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Gourmet Thai Satay (min 2 sticks)', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '8.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Ginger Lovers', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '9.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Oyster Sauce Special', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '10.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'King Prawns Satay', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '11.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Cashew Nuts Special', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '12.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pad Thai', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '13.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Thai Green Curry', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '14.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Thai Red Curry', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '15.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Panang Curry', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '16.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Chicken Macadamia', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '17.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Five Star Chicken', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '1.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Choo Chee GoongCh', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '2.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sweet & Sour Special', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '3.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Tom Kha Soup', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '4.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sukiyaki Soup', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '6.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Thai Fried Rice', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '7.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Larb Salad', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '8.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Crispy Fish Fillet On Rice', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '9.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Num Tok', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '10.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Grilled Pork', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '11.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sweet Chilli Snapper', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '12.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Steamed Snapper', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '13.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Deep Fried Snapper', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'soups',
                    'image' => '14.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                //noodles
                [
                    'name' => 'Pad Kee Moa', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '2.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Stewed Beef Noodles', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '15.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Rad Nah', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '16.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Tom Yum Noodles', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '17.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pad See You', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '1.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sizzling Beef', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '2.jpg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pra Ram', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '3.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pad Ped Phed Yang', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '4.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Thai Yellow Curry', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '5.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Thai Massaman Curry', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '6.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Mee Pad Tom Yum', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '7.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Yum Neau', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '8.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Roast Duck Thai Larb', 
                    'price' => 0, 
                    'ingredients' => '', 
                    'type' => 'noodles',
                    'image' => '9.jpeg',
                    'restaurant_id' => 10,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
            ]
        );
    }
}
