<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UmiSushi extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert(
            [
                //donburi
                [
                    'name' => 'Teriyaki Eel Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '1.jpg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'ChickenKaraage Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '3.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Oyako Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '4.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Spicy Pepper Chicken Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '5.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Gyu Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '6.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Katsu Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '7.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Teriyaki Tofu Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '8.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Grilled Salmon Don', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '9.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Salmon Karaage Don', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'donburi',
                    'image' => '11.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                //salad noodles
                [
                    'name' => 'Teriyaki Chicken Salad', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'salad and noodles',
                    'image' => '12.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Grilled Salmon Salad', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'salad and noodles',
                    'image' => '13.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sashimi Carpaccio Salad Fresh King Salmon', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'salad and noodles',
                    'image' => '15.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Karaage Tofu Salad with citrus ponzu dressing', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'salad and noodles',
                    'image' => '16.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Grilled Seafood Salad Teriyaki or garlic sauteed', 
                    'price' => 14, 
                    'ingredients' => '', 
                    'type' => 'salad and noodles',
                    'image' => '17.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Creamy Soy Noodle Salad', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'salad and noodles',
                    'image' => '12.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                // katsu and yaki
                [
                    'name' => 'Ton katsu', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '13.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Chicken katsu', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '3.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Katsu curry', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '4.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Teriyaki Chicken', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '5.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Spicy Chilli Pork Yakiniku Beef', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '6.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pepper Teriyaki Calamari', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '7.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Yaki Gyoza Set (14 pcs)', 
                    'price' => 11, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '8.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Gyoza Only (12 pcs)', 
                    'price' => 9, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '9.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Teriyaki Tofu Eggplant', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'katsu and yaki',
                    'image' => '10.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                //noodle soup
                [
                    'name' => 'Chicken Yaki Soba orYaki Udon', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '11.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Seafood Yaki Soba orYaki Udon', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '12.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Chicken Udon', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '13.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Chicken Udon', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '16.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Seafood Udon', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '15.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Vegetable Udon', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '17.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Curry Udon', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '3.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pepper Spiced Udon', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '4.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Chicken Ramen (miso or shoyu)', 
                    'price' => 12, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '5.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Seafoo Ramen(miso or shoyu)', 
                    'price' => 13, 
                    'ingredients' => '', 
                    'type' => 'noodle soups',
                    'image' => '6.jpeg',
                    'restaurant_id' => 11,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
            ]
        );
    }
}
